/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "encbfyyrpyaqwiqtptpm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuY2JmeXlycHlhcXdpcXRwdHBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjA4MTEsImV4cCI6MjA3MDg5NjgxMX0.OaiXZBCOJitYB1--Bg11i2S7ivs4IV9xjaZtT5yrMWc"